// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacMan.Server.Data;

#nullable disable

namespace PacMan.Server.Migrations
{
    [DbContext(typeof(PacManDbContext))]
    partial class PacManDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A fund focusing on tech startups",
                            Name = "Tech Growth Fund"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A fund focusing on healthcare innovations",
                            Name = "Healthcare Innovation Fund"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A fund focusing on renewable energy",
                            Name = "Green Energy Fund"
                        });
                });

            modelBuilder.Entity("PacMan.Server.Models.FundInvestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Commitment")
                        .HasColumnType("int");

                    b.Property<int>("Distribution")
                        .HasColumnType("int");

                    b.Property<int>("FundId")
                        .HasColumnType("int");

                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<int>("PaidIn")
                        .HasColumnType("int");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.HasIndex("InvestorId");

                    b.ToTable("FundInvestors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commitment = 1000000,
                            Distribution = 200000,
                            FundId = 1,
                            InvestorId = 1,
                            PaidIn = 500000,
                            Profit = 300000
                        },
                        new
                        {
                            Id = 2,
                            Commitment = 2000000,
                            Distribution = 400000,
                            FundId = 1,
                            InvestorId = 2,
                            PaidIn = 1000000,
                            Profit = 600000
                        },
                        new
                        {
                            Id = 3,
                            Commitment = 1500000,
                            Distribution = 300000,
                            FundId = 1,
                            InvestorId = 3,
                            PaidIn = 750000,
                            Profit = 450000
                        },
                        new
                        {
                            Id = 4,
                            Commitment = 1200000,
                            Distribution = 240000,
                            FundId = 2,
                            InvestorId = 4,
                            PaidIn = 600000,
                            Profit = 360000
                        },
                        new
                        {
                            Id = 5,
                            Commitment = 2500000,
                            Distribution = 500000,
                            FundId = 2,
                            InvestorId = 5,
                            PaidIn = 1250000,
                            Profit = 750000
                        },
                        new
                        {
                            Id = 6,
                            Commitment = 1800000,
                            Distribution = 360000,
                            FundId = 2,
                            InvestorId = 6,
                            PaidIn = 900000,
                            Profit = 540000
                        },
                        new
                        {
                            Id = 7,
                            Commitment = 1100000,
                            Distribution = 220000,
                            FundId = 3,
                            InvestorId = 7,
                            PaidIn = 550000,
                            Profit = 330000
                        },
                        new
                        {
                            Id = 8,
                            Commitment = 1300000,
                            Distribution = 260000,
                            FundId = 3,
                            InvestorId = 8,
                            PaidIn = 650000,
                            Profit = 390000
                        },
                        new
                        {
                            Id = 9,
                            Commitment = 1700000,
                            Distribution = 340000,
                            FundId = 3,
                            InvestorId = 9,
                            PaidIn = 850000,
                            Profit = 510000
                        });
                });

            modelBuilder.Entity("PacMan.Server.Models.Investor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Investors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alice Davis"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Michael Brown"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Laura Wilson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chris Evans"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Olivia Taylor"
                        },
                        new
                        {
                            Id = 9,
                            Name = "David Harris"
                        });
                });

            modelBuilder.Entity("PacMan.Server.Models.FundInvestor", b =>
                {
                    b.HasOne("Fund", "Fund")
                        .WithMany("FundInvestors")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PacMan.Server.Models.Investor", "Investor")
                        .WithMany("FundInvestors")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("Fund", b =>
                {
                    b.Navigation("FundInvestors");
                });

            modelBuilder.Entity("PacMan.Server.Models.Investor", b =>
                {
                    b.Navigation("FundInvestors");
                });
#pragma warning restore 612, 618
        }
    }
}
